name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境中运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 设置 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 安装依赖

      - name: Set up environment variables
        run: |
          echo "OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}" >> $GITHUB_ENV  # 将 Secrets 设置为环境变量
          echo "OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}" >> $GITHUB_ENV  # 设置阿里云访问密钥

      - name: Deploy Streamlit app
        run: |
          streamlit run math_1.py  # 部署 Streamlit 应用
